### PR TITLE
pexec

### PR DESCRIPTION
**Pull request by dwsJason**
Check in updated version of pexec

### CODE REVIEW

**Comment by dwsJason** [comment]
If the version checked in has the running man, then it's the latest version, and this can be disregarded.  I'm happy to provide it again later today on the Discord.

**Comment by rmsk2** [comment]
Hi, I have synced the pexec fork in FoenixRetro  (https://github.com/FoenixRetro/f256-pexec) to your latest version in https://github.com/dwsJason/f256_pexec and used that version to build a firmware package. The version that is in the package has the running man.

**Comment by rmsk2** [comment]
So should I close the pull request?

**Comment by rmsk2** [comment]
pexec version has been updated independently of this pull request.

**Pull request closed without merging**
